### ISSUE TITLE
请问这个支持udp转发么？

### ISSUE THREAD

**Issue by yoyosuka** [oddrationale/docker-shadowsocks#6]
需要架个支持udp转发的来玩游戏。请把udp这块的内容写一下吧。我是新手，谢谢。

**Comment by windhamwong** [comment]
請看Dockerfile........ 這是純安裝, 其他設定請在host設定。
伸手不是最好的解決方法

**Comment by Prussia** [comment]
https://github.com/shadowsocks/shadowsocks/blob/master/Dockerfile
Features:

TCP & UDP support
User management API
TCP Fast Open
Workers and graceful restart
Destination IP blacklist
